{inputs, ...}: {
  imports = [
    inputs.git-hooks.flakeModule
  ];

  perSystem = {
    config,
    pkgs,
    ...
  }: {
    # Use prek (Rust reimplementation of pre-commit) instead of the upstream
    # Python pre-commit. Drop-in compatible, noticeably faster startup, and
    # git-hooks.nix has first-class support for it.
    pre-commit.settings.package = pkgs.prek;

    pre-commit.settings.hooks = {
      # git-hooks.nix has no built-in gitleaks hook, so wire one up by
      # hand against the gitleaks package from nixpkgs. `protect --staged`
      # scans only the changes about to be committed; `--redact` keeps
      # any findings out of terminal scrollback / screen shares.
      gitleaks = {
        enable = true;
        name = "gitleaks";
        entry = "${pkgs.gitleaks}/bin/gitleaks protect --staged --verbose --redact";
        language = "system";
        pass_filenames = false;
      };

      # Formatter for Nix. Cheap, keeps whitespace drift out of the tree.
      # The hardware config is regenerated by `nixos-anywhere`'s
      # `nixos-generate-config`, so keep its upstream formatting
      # to avoid a reformat/regen tug-of-war on every reinstall.
      alejandra = {
        enable = true;
        excludes = ["^hosts/foundry/hardware-configuration\\.nix$"];
      };
    };

    # `nix develop` (or direnv via `.envrc`) drops you into this shell;
    # git-hooks.nix's shellHook installs/refreshes .git/hooks/pre-commit
    # the first time it runs. `nix flake check` also runs these hooks
    # against the tree (the flakeModule wires it up as checks.pre-commit
    # automatically), which is the same gate CI uses.
    devShells.default = config.pre-commit.devShell;
  };
}
